DROP TABLE IF EXISTS EMPLOYEE;  
CREATE TABLE EMPLOYEE (  
id int NOT NULL AUTO_INCREMENT,  
first_name VARCHAR(255) NOT NULL,  
last_name VARCHAR(255) NOT NULL,
date_of_birth DATE NOT NULL,
addressLine1 VARCHAR(255) NOT NULL,
addressLine2 VARCHAR(255),
city VARCHAR(255) NOT NULL,
state VARCHAR(255) NOT NULL,
country VARCHAR(255) NOT NULL,
zip_code VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);  